services:
  - type: web
    name: orphelin-asbl
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_admin
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
